"use client";
import { useState } from 'react';

const SuggestionInterface = ({ documentId }) => {
  const [suggestions, setSuggestions] = useState([]);
  const [isLoaded, setIsLoaded] = useState(false); // Track if suggestions are loaded
  const [notification, setNotification] = useState(''); // State for the notification

  // Fetch suggestions from the API
  const fetchSuggestions = async () => {
    try {
      const response = await fetch(`http://127.0.0.1:5555/documents/${documentId}/suggestions`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('JWT')}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to fetch suggestions');
      }

      const data = await response.json();
      setSuggestions(data.suggestions);
      setIsLoaded(true); // Mark that suggestions are loaded
    } catch (err) {
      console.error(err.message);
    }
  };

  // Handle accept suggestion action
  const handleAccept = async (id) => {
    try {
      const response = await fetch(`http://127.0.0.1:5555/suggestions/accept/${id}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('JWT')}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to accept suggestion');
      }

      const data = await response.json();
      setNotification('Suggestion accepted'); // Display notification
      setTimeout(() => setNotification(''), 3000); // Hide notification after 3 seconds

      // Re-fetch suggestions to show updated list
      fetchSuggestions();

    } catch (err) {
      console.error(err.message);
      setNotification('Failed to accept suggestion');
      setTimeout(() => setNotification(''), 3000); // Hide notification after 3 seconds
    }
  };

  // Handle reject suggestion action
  const handleReject = async (id) => {
    try {
      const response = await fetch(`http://127.0.0.1:5555/suggestions/deny/${id}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${localStorage.getItem('JWT')}`,
        },
      });

      if (!response.ok) {
        throw new Error('Failed to deny suggestion');
      }

      const data = await response.json();
      setNotification('Suggestion denied'); // Display notification
      setTimeout(() => setNotification(''), 3000); // Hide notification after 3 seconds

      // Re-fetch suggestions to show updated list
      fetchSuggestions();

    } catch (err) {
      console.error(err.message);
      setNotification('Failed to deny suggestion');
      setTimeout(() => setNotification(''), 3000); // Hide notification after 3 seconds
    }
  };

  return (
    <>
      
      <div className="container">
        <div className="row align-items-center justify-content-start">
          <div className="col-lg-5">
            <h1 className="heading" data-aos="fade-up">Suggestions</h1>
            <p className="mb-5" data-aos="fade-up">Review and apply suggestions generated by RefineDocs AI for document improvements.</p>
          </div>
        </div>
      </div>

      {/* Notification message */}
      {notification && <div className="alert alert-success">{notification}</div>}


      {/* Suggestions Section */}
      <div className="section">
        <div className="container">
          <div className="row mb-5">
            {suggestions.length > 0 && (
              suggestions.map((suggestion) => (
                <div className="col-lg-6" key={suggestion.id}>
                  <div className="suggestion-entry">
                    <p>{suggestion.suggestion_text}</p>
                    <div className="btn-group">
                      <button onClick={() => handleAccept(suggestion.id)} className="btn btn-sm btn-outline-success">Accept</button>
                      <button onClick={() => handleReject(suggestion.id)} className="btn btn-sm btn-outline-danger">Reject</button>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>

          {/* Load suggestions button */}
          {!isLoaded && (
            <div className="row">
              <div className="col-lg-12">
                <button onClick={fetchSuggestions} className="upload-button mt-44">Load Suggestions</button>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default SuggestionInterface;
