import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from 'next/script';

import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/Footer";
import WhatsappFloatingButton from "@/components/WhatsappButton/WhatsappFloatingButton"
// import TawkMessenger from '@/components/TawkMessenger/TawkMessenger';
import './styles/custom-bootstrap.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossOrigin="anonymous"
        />
      </Head>
      <body className={inter.className}>
        <Navbar /> 
        {/* <nav class="navbar navbar-expand-lg navbar-light bg-transparent fixed-top">
          <div class="container-fluid d-flex justify-content-between">
            <Image src="/images/logo.png" alt="logo" className="logo-fluid pt-4" width={126} height={175} />
            <button class="navbar-toggler text-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link text-info" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-info" href="/about">About Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-info" href="/services">Services</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-info" href="/contact">Contact</a>
                </li>
                {/* <li class="nav-item">
                  <a class="nav-link text-info" href="/blog" tabindex="-1" aria-disabled="true">Blog</a>
                </li> 
              </ul>
            </div>
          </div>
        </nav> */}

        {children}

        {/* <TawkMessenger /> */}
        <WhatsappFloatingButton />
        <Footer />
        {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>*/}
        <Script
          strategy="afterInteractive"
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"
        />
      </body>
    </html>
  );
}
