"""change column

Revision ID: 87e57f6f7006
Revises: 908a86dd1291
Create Date: 2024-09-18 14:03:45.291103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e57f6f7006'
down_revision = '908a86dd1291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
