"""correct document model

Revision ID: c45550dcc754
Revises: 87e57f6f7006
Create Date: 2024-09-18 20:37:33.580230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45550dcc754'
down_revision = '87e57f6f7006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'suggestions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('suggestions', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
